### ISSUE TITLE
Rendering - Headline and Image Size

### ISSUE THREAD

**Issue by Dubidubiduu** [eneiluj/welcome#10]
![welcome_rendering](https://user-images.githubusercontent.com/34820982/108113671-14b9e880-7098-11eb-9378-72d31bf2bea0.png)

Just switched to another .md file. It was created by text editor. The headline is to big and the image too small.

Headline I could fix by switching to h5 or so, while I use the information at another place I then would then need to create two files for parsing at two different places.

**Comment by eneiluj** [comment]
Images are now a bit bigger (100px height) and `<h*>` are all a bit smaller.

![welcome](https://user-images.githubusercontent.com/11291457/108349680-94080300-71e3-11eb-99c5-c29cf5d5635a.png)

This is available in v0.0.4 which was released.

**Comment by eneiluj** [comment]
Any better with v0.0.4?

**Comment by Dubidubiduu** [comment]
Yeah, guess this is much better.
