### ISSUE TITLE
Markdown not being rendered properly

### ISSUE THREAD

**Issue by RussellNS** [eneiluj/welcome#17]
First off, love the widget!  It's simple, and does exactly (almost) what I was hoping for.

However, I am running into an issue where the markdown that I'm creating inside Nextcloud is not being displayed the same on the widget.  It seems that it renders some/most markdown correctly, but seems to struggle with formatting (bullet indention, sub-bullet indention, bold, extra blank lines, etc.).

I think the best way to show you what I'm getting is with screenshots.

This is a markdown file being edited (and saved) in Nextcloud.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Welcome Issue 02](https://user-images.githubusercontent.com/20754684/129032840-9bb5104b-a757-4212-9310-4dac9d9b75ed.png)

This is what's being displayed in the Welcome widget on the dashboard.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![Welcome Issue 01](https://user-images.githubusercontent.com/20754684/129032880-b5b02358-d4fd-4a9b-bfcb-5891cab3e545.png)

I've already read on another issue that you're fairly busy on other things currently.  I respect that.  Any help or direction would be appreciated.

Thank you for any attention you can give to this.

**Comment by eneiluj** [comment]
Hi, thanks for the bug report.

Thankfully those issues are just style related (meaning the markdown parser works fine).
It's now fixed and available in latest nightly build (v1.0.0-1-nightly).

![welc](https://user-images.githubusercontent.com/11291457/130430956-a79ba3b5-0899-46de-90e2-5d01f73ef118.png)

You can download the nightly manually from the appstore or you can also simply get it with an occ command:
```
occ app:update --allow-unstable welcome
```
When you want to get back to normal releases, just disable and remove the app from app settings and reinstall it. You won't loose any data.

If you try it and confirm it's working fine, I'll make a release.

**Comment by RussellNS** [comment]
I just tried it.  Confirming that it works like a champ!  Thank you!

Putting this out here for others:  I assume due to some other reason (API, translation, architectual, whatever), the Welcome app doesn't show blank lines.  I was able to get around that by manually typing <br> in my md file to achieve the same affect.

All in all, very happy, and again, thank you!

**Comment by eneiluj** [comment]
Thanks for your feedback and your enthusiasm!

> the Welcome app doesn't show blank lines

It might be a limitation of the markdown parser library. I'll have a look.
You could open a new issue for that to make sure we don't forget about this problem.

**Comment by RussellNS** [comment]
I'll do that, and include the workaround.
