### ISSUE TITLE
Uncaught syntax error theming admin page - No options available

### ISSUE THREAD

**Issue by Dubidubiduu** [eneiluj/welcome#6]
3. Now I just got a
`Uncaught SyntaxError: expected expression, got '<'welcome-adminSettings.js:1`, but actually I can't find this file. When I click on shown file in my browser console it shows source code of `view-source:/index.php/apps/dashboard/`.

And I guess for this I don't see any options.

**Comment by eneiluj** [comment]
I don't exactly get what happens.
1. How did you install the app? Are you sure you're using v0.0.2?
2. Do you see this `SyntaxError` when loading the theming admin settings page?

I tried v0.0.2 on a freshly installed NC 20 and it runs fine. Let's find out what happens on your side.

**Comment by Dubidubiduu** [comment]
> * How did you install the app? Are you sure you're using v0.0.2?
> 
> * Do you see this `SyntaxError` when loading the theming admin settings page?

1. I downloaded, unpacked, then renamed to get rid of the version number in folder name, then activated. In app backend it says it is 0.0.2.

**Comment by Dubidubiduu** [comment]
Also fixed with 0.3
