### ISSUE TITLE
No update for 20.0.7

### ISSUE THREAD

**Issue by Dubidubiduu** [eneiluj/welcome#7]
4. Using nextcloud 20.0.5, I could update to 20.0.7, but welcome hasn't got a update for this.

**Comment by eneiluj** [comment]
What do you mean? This app is compatible with any Nextcloud version between 20 and 21.

**Comment by Dubidubiduu** [comment]
Maybe this is just just default behaviour for apps not installed via app store?

![welcomenoupdate](https://user-images.githubusercontent.com/34820982/107833511-ce147780-6d93-11eb-8b5d-99fa2cc90060.PNG)
