### ISSUE TITLE
Rendering readme.md - Ugly line breaks

### ISSUE THREAD

**Issue by Dubidubiduu** [eneiluj/welcome#9]
![welcome_widget](https://user-images.githubusercontent.com/34820982/108111642-43828f80-7095-11eb-9ef8-5f510c1a6161.PNG)
Propably not highest priority, but still. My list has ugly line breaks.

**Comment by eneiluj** [comment]
I can't reproduce the issue. Could you provide the markdown content?

**Comment by Dubidubiduu** [comment]
In part it has been this:
`.
2. **Stell dich vor:** Stell dich in den yyy in [unserer digitalen Kneipe](https://cloud.xxx.de/index.php/call/grmlgrml) vor.
3. **Sitzungen:** Alles zur aktuellen Sitzung liegt unter [/xxx/Organisation/Sitzungen/Z_](https://cloud.xxx.de/index.php/f/361770)*[Aktuelle](https://cloud.xxx.de/index.php/f/361770)*[_Sitzung](https://cloud.xxx.de/index.php/f/361770).
4. **Talk**: Unsere Absprachen finden überwiegend in [Talk](https://cloud.xxx.de/index.php/apps/spreed/) statt. Nutze die App "**Nextcloud Talk**" auf deinem Smartphone um im Austausch zu bleiben.\`

and then there is something more in the file, which I haven't pasted here. I just changed to another file, so I don't have the problem any longer. Closing for now.
